spring:
  application:
    name: Payment-service

  datasource:
    url: jdbc:mysql://localhost:3306/spms_payment_db
    username: root
    password: harshima@123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

