spring:
  application:
    name: Parking-space-service

  datasource:
    url: jdbc:mysql://localhost:3306/spms
    username: root
    password: harshima@123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8081
